Table PERSON {
  person_id integer '人員ID' 
  gender_concept_id integer '性別概念ID'
  year_of_birth integer '出生年'
  month_of_birth integer '出生月' 
  day_of_birth integer '出生日'
  birth_datetime timestamp '出生時間'
  race_concept_id integer '種族概念ID'
  ethnicity_concept_id integer '族裔概念ID'  
  location_id integer '位置ID'
  provider_id integer '提供者ID'
  care_site_id integer '護理場所ID'
  person_source_value varchar(50) '人員來源值'
  gender_source_value varchar(50) '性別來源值'
  gender_source_concept_id integer '性別來源概念ID'
  race_source_value varchar(50) '種族來源值'
  race_source_concept_id integer '種族來源概念ID'
  ethnicity_source_value varchar(50) '族裔來源值'
  ethnicity_source_concept_id integer '族裔來源概念ID'
}

Table OBSERVATION_PERIOD {
  observation_period_id integer '觀察期ID'
  person_id integer '人員ID'
  observation_period_start_date date '觀察期開始日期'
  observation_period_end_date date '觀察期結束日期'  
  period_type_concept_id integer '期間類型概念ID'
}

Table VISIT_OCCURRENCE {
  visit_occurrence_id integer '就診發生ID'
  person_id integer '人員ID'
  visit_concept_id integer '就診概念ID'
  visit_start_date date '就診開始日期'
  visit_start_datetime timestamp '就診開始時間'
  visit_end_date date '就診結束日期' 
  visit_end_datetime timestamp '就診結束時間'
  visit_type_concept_id integer '就診類型概念ID'
  provider_id integer '提供者ID'
  care_site_id integer '護理場所ID'
  visit_source_value varchar(50) '就診來源值'
  visit_source_concept_id integer '就診來源概念ID'
  admitted_from_concept_id integer '入院來源概念ID'
  admitted_from_source_value varchar(50) '入院來源值'
  discharged_to_concept_id integer '出院目的地概念ID'
  discharged_to_source_value varchar(50) '出院目的地值'
  preceding_visit_occurrence_id integer '前次就診發生ID'
}
Table VISIT_DETAIL {
  visit_detail_id integer '就診明細ID'
  person_id integer '人員ID'
  visit_detail_concept_id integer '就診明細概念ID'
  visit_detail_start_date date '就診明細開始日期'
  visit_detail_start_datetime timestamp '就診明細開始時間'
  visit_detail_end_date date '就診明細結束日期'
  visit_detail_end_datetime timestamp '就診明細結束時間'
  visit_detail_type_concept_id integer '就診明細類型概念ID'
  provider_id integer '提供者ID'
  care_site_id integer '護理場所ID'
  visit_detail_source_value varchar(50) '就診明細來源值'
  visit_detail_source_concept_id integer '就診明細來源概念ID'
  admitted_from_concept_id integer '入院來源概念ID'
  admitted_from_source_value varchar(50) '入院來源值'
  discharged_to_source_value varchar(50) '出院目的地值'
  discharged_to_concept_id integer '出院目的地概念ID'
  preceding_visit_detail_id integer '前次就診明細ID'
  parent_visit_detail_id integer '父就診明細ID'
  visit_occurrence_id integer '就診發生ID'
}

Table CONDITION_OCCURRENCE {
  condition_occurrence_id integer '疾病發生ID'
  person_id integer '人員ID'
  condition_concept_id integer '疾病概念ID'
  condition_start_date date '疾病開始日期'
  condition_start_datetime timestamp '疾病開始時間'
  condition_end_date date '疾病結束日期'
  condition_end_datetime timestamp '疾病結束時間'
  condition_type_concept_id integer '疾病類型概念ID'
  condition_status_concept_id integer '疾病狀態概念ID'
  stop_reason varchar(20) '停止原因'
  provider_id integer '提供者ID'
  visit_occurrence_id integer '就診發生ID'
  visit_detail_id integer '就診明細ID'
  condition_source_value varchar(50) '疾病來源值'
  condition_source_concept_id integer '疾病來源概念ID'
  condition_status_source_value varchar(50) '疾病狀態來源值'
}

// ...上面表格

Table DRUG_EXPOSURE {
  drug_exposure_id integer '藥物曝露ID'  
  person_id integer '人員ID'
  drug_concept_id integer '藥物概念ID'
  drug_exposure_start_date date '藥物曝露開始日期'
  drug_exposure_start_datetime timestamp '藥物曝露開始時間'
  drug_exposure_end_date date '藥物曝露結束日期'
  drug_exposure_end_datetime timestamp '藥物曝露結束時間'
  verbatim_end_date date '確切結束日期'
  drug_type_concept_id integer '藥物類型概念ID'
  stop_reason varchar(20) '停止原因'
  refills integer '重fill次數'
  quantity numeric '數量'
  days_supply integer '供應天數' 
  sig text '藥物使用說明'
  route_concept_id integer '給藥途徑概念ID'
  lot_number varchar(50) '批號'
  provider_id integer '提供者ID'
  visit_occurrence_id integer '就診發生ID'
  visit_detail_id integer '就診明細ID'
  drug_source_value varchar(50) '藥物來源值'
  drug_source_concept_id integer '藥物來源概念ID'
  route_source_value varchar(50) '給藥途徑來源值'
  dose_unit_source_value varchar(50) '劑量單位來源值'
}

Table PROCEDURE_OCCURRENCE {
  procedure_occurrence_id integer '程序發生ID'
  person_id integer '人員ID'
  procedure_concept_id integer '程序概念ID'
  procedure_date date '程序日期'
  procedure_datetime timestamp '程序時間'
  procedure_end_date date '程序結束日期'
  procedure_end_datetime timestamp '程序結束時間'
  procedure_type_concept_id integer '程序類型概念ID'
  modifier_concept_id integer '修飾概念ID'
  quantity integer '數量'
  provider_id integer '提供者ID'
  visit_occurrence_id integer '就診發生ID'
  visit_detail_id integer '就診明細ID' 
  procedure_source_value varchar(50) '程序來源值'
  procedure_source_concept_id integer '程序來源概念ID'
  modifier_source_value varchar(50) '修飾來源值'
}

Table DEVICE_EXPOSURE {
  device_exposure_id integer '設備曝露ID'
  person_id integer '人員ID'
  device_concept_id integer '設備概念ID'
  device_exposure_start_date date '設備曝露開始日期'
  device_exposure_start_datetime timestamp '設備曝露開始時間'
  device_exposure_end_date date '設備曝露結束日期'
  device_exposure_end_datetime timestamp '設備曝露結束時間'
  device_type_concept_id integer '設備類型概念ID'
  unique_device_id varchar(255) '唯一設備ID'
  production_id varchar(255) '生產ID'
  quantity integer '數量'
  provider_id integer '提供者ID'
  visit_occurrence_id integer '就診發生ID'
  visit_detail_id integer '就診明細ID'
  device_source_value varchar(50) '設備來源值'
  device_source_concept_id integer '設備來源概念ID'
  unit_concept_id integer '單位概念ID'
  unit_source_value varchar(50) '單位來源值'
  unit_source_concept_id integer '單位來源概念ID'
}

Table MEASUREMENT {
  measurement_id integer '測量ID'
  person_id integer '人員ID'  
  measurement_concept_id integer '測量概念ID'
  measurement_date date '測量日期'
  measurement_datetime timestamp '測量時間'
  measurement_time varchar(10) '測量時間'
  measurement_type_concept_id integer '測量類型概念ID'
  operator_concept_id integer '操作子概念ID'
  value_as_number numeric '數值結果'
  value_as_concept_id integer '概念結果'
  unit_concept_id integer '單位概念ID'
  range_low numeric '範圍下限'
  range_high numeric '範圍上限'
  provider_id integer '提供者ID'
  visit_occurrence_id integer '就診發生ID'
  visit_detail_id integer '就診明細ID'
  measurement_source_value varchar(50) '測量來源值'
  measurement_source_concept_id integer '測量來源概念ID'
  unit_source_value varchar(50) '單位來源值'
  unit_source_concept_id integer '單位來源概念ID'
  value_source_value varchar(50) '值來源值'
  measurement_event_id integer '測量事件ID'
  meas_event_field_concept_id integer '測量事件欄位概念ID'
}

Table OBSERVATION {
  observation_id integer '觀察ID'
  person_id integer '人員ID'
  observation_concept_id integer '觀察概念ID'
  observation_date date '觀察日期'
  observation_datetime timestamp '觀察時間'
  observation_type_concept_id integer '觀察類型概念ID'
  value_as_number numeric '數值結果'
  value_as_string varchar(60) '字串結果'
  value_as_concept_id integer '概念結果'
  qualifier_concept_id integer '修飾概念ID'
  unit_concept_id integer '單位概念ID'
  provider_id integer '提供者ID'
  visit_occurrence_id integer '就診發生ID'
  visit_detail_id integer '就診明細ID'
  observation_source_value varchar(50) '觀察來源值'
  observation_source_concept_id integer '觀察來源概念ID'
  unit_source_value varchar(50) '單位來源值'
  qualifier_source_value varchar(50) '修飾來源值'
  value_source_value varchar(50) '值來源值'
  observation_event_id integer '觀察事件ID'
  obs_event_field_concept_id integer '觀察事件欄位概念ID' 
}

Table DEATH {
  person_id integer '人員ID'  
  death_date date '死亡日期'
  death_datetime timestamp '死亡時間'
  death_type_concept_id integer '死亡類型概念ID'
  cause_concept_id integer '死因概念ID'
  cause_source_value varchar(50) '死因來源值'
  cause_source_concept_id integer '死因來源概念ID'
}

Table NOTE {
  note_id integer '筆記ID'
  person_id integer '人員ID'
  note_date date '筆記日期'
  note_datetime timestamp '筆記時間'
  note_type_concept_id integer '筆記類型概念ID'
  note_class_concept_id integer '筆記類別概念ID'
  note_title varchar(250) '筆記標題'
  note_text text '筆記內容'
  encoding_concept_id integer '編碼概念ID'
  language_concept_id integer '語言概念ID'
  provider_id integer '提供者ID'
  visit_occurrence_id integer '就診發生ID'
  visit_detail_id integer '就診明細ID'
  note_source_value varchar(50) '筆記來源值'
  note_event_id integer '筆記事件ID'
  note_event_field_concept_id integer '筆記事件欄位概念ID'
}

Table NOTE_NLP {
  note_nlp_id integer '筆記NLP ID' 
  note_id integer '筆記ID'
  section_concept_id integer '段落概念ID'
  snippet varchar(250) '摘錄'
  "offset" varchar(50) '偏移量'
  lexical_variant varchar(250) '詞彙變體'
  note_nlp_concept_id integer '筆記NLP概念ID'
  note_nlp_source_concept_id integer '筆記NLP來源概念ID'
  nlp_system varchar(250) 'NLP系統'
  nlp_date date 'NLP日期'
  nlp_datetime timestamp 'NLP時間'
  term_exists varchar(1) '術語是否存在'
  term_temporal varchar(50) '術語時態'
  term_modifiers varchar(2000) '術語修飾詞'
}

Table SPECIMEN {
  specimen_id integer '檢體ID'
  person_id integer '人員ID'
  specimen_concept_id integer '檢體概念ID'
  specimen_type_concept_id integer '檢體類型概念ID'
  specimen_date date '檢體日期'
  specimen_datetime timestamp '檢體時間'
  quantity numeric '數量'
  unit_concept_id integer '單位概念ID'
  anatomic_site_concept_id integer '解剖部位概念ID'
  disease_status_concept_id integer '疾病狀態概念ID'
  specimen_source_id varchar(50) '檢體來源ID'
  specimen_source_value varchar(50) '檢體來源值'
  unit_source_value varchar(50) '單位來源值'
  anatomic_site_source_value varchar(50) '解剖部位來源值'
  disease_status_source_value varchar(50) '疾病狀態來源值'
}